"""baseline schema

Revision ID: ca24190e0bd6
Revises:
Create Date: 2026-10-09 14:43:35.187725
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ca24190e0bd6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_key", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("component_id", sa.String(length=128), nullable=False),
        sa.Column("component_type", sa.String(length=32), nullable=False),
        sa.Column("alert_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("opened_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("priority_level", sa.String(length=32), nullable=False),
        sa.Column("failure_probability", sa.Float(), nullable=False),
        sa.Column("risk_horizon_hours", sa.Integer(), nullable=True),
        sa.Column("model_confidence", sa.Float(), nullable=False),
        sa.Column("technical_severity", sa.Float(), nullable=False),
        sa.Column("commercial_severity", sa.Float(), nullable=False),
        sa.Column("affected_power_mw", sa.Float(), nullable=False),
        sa.Column("affected_energy_mwh", sa.Float(), nullable=False),
        sa.Column("revenue_at_risk_eur", sa.Float(), nullable=False),
        sa.Column("anomaly_score", sa.Float(), nullable=True),
        sa.Column("limiting_factor", sa.String(length=64), nullable=True),
        sa.Column("supporting_signals_json", sa.String(), nullable=False),
        sa.Column("source_versions_json", sa.String(), nullable=False),
        sa.Column("data_provenance", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alert_key", name="uq_alert_key"),
    )
    op.create_index("ix_alert_asset_status", "alerts", ["asset_id", "status"], unique=False)
    op.create_index(
        "ix_alert_status_priority", "alerts", ["status", "priority_score"], unique=False
    )
    op.create_index(op.f("ix_alerts_alert_key"), "alerts", ["alert_key"], unique=True)
    op.create_index(op.f("ix_alerts_asset_id"), "alerts", ["asset_id"], unique=False)
    op.create_index(op.f("ix_alerts_component_id"), "alerts", ["component_id"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_table(
        "anomaly_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anomaly_event_id", sa.String(length=64), nullable=False),
        sa.Column("component_id", sa.String(length=128), nullable=False),
        sa.Column("component_type", sa.String(length=32), nullable=False),
        sa.Column("detector_name", sa.String(length=64), nullable=False),
        sa.Column("detector_version", sa.String(length=64), nullable=False),
        sa.Column("start_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("peak_score", sa.Float(), nullable=False),
        sa.Column("mean_score", sa.Float(), nullable=False),
        sa.Column("supporting_signals_json", sa.String(), nullable=False),
        sa.Column("feature_set_version", sa.String(length=32), nullable=False),
        sa.Column("data_provenance", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anomaly_event_id", name="uq_anomaly_event_id"),
    )
    op.create_index(
        "ix_anomaly_component_start",
        "anomaly_events",
        ["component_id", "start_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anomaly_events_anomaly_event_id"),
        "anomaly_events",
        ["anomaly_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anomaly_events_component_id"), "anomaly_events", ["component_id"], unique=False
    )
    op.create_index(
        op.f("ix_anomaly_events_start_timestamp"),
        "anomaly_events",
        ["start_timestamp"],
        unique=False,
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("rated_power_mw", sa.Float(), nullable=False),
        sa.Column("rated_energy_mwh", sa.Float(), nullable=False),
        sa.Column("data_provenance", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_asset_id"), "assets", ["asset_id"], unique=True)
    op.create_table(
        "availability_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("technical_availability", sa.Float(), nullable=False),
        sa.Column("rack_technical_availability", sa.Float(), nullable=False),
        sa.Column("pcs_technical_availability", sa.Float(), nullable=False),
        sa.Column("known_component_fraction", sa.Float(), nullable=False),
        sa.Column("available_discharge_power_mw", sa.Float(), nullable=False),
        sa.Column("available_charge_power_mw", sa.Float(), nullable=False),
        sa.Column("available_discharge_energy_mwh", sa.Float(), nullable=False),
        sa.Column("available_charge_energy_mwh", sa.Float(), nullable=False),
        sa.Column("discharge_power_availability", sa.Float(), nullable=False),
        sa.Column("charge_power_availability", sa.Float(), nullable=False),
        sa.Column("discharge_energy_availability", sa.Float(), nullable=False),
        sa.Column("charge_energy_availability", sa.Float(), nullable=False),
        sa.Column("requested_power_mw", sa.Float(), nullable=False),
        sa.Column("requested_power_availability", sa.Float(), nullable=True),
        sa.Column("requested_energy_availability", sa.Float(), nullable=True),
        sa.Column("sustainable_request_duration_hours", sa.Float(), nullable=True),
        sa.Column("available_racks", sa.Integer(), nullable=False),
        sa.Column("unknown_racks", sa.Integer(), nullable=False),
        sa.Column("available_pcs", sa.Integer(), nullable=False),
        sa.Column("unknown_pcs", sa.Integer(), nullable=False),
        sa.Column("limiting_factor", sa.String(length=64), nullable=False),
        sa.Column("limiting_factors_json", sa.String(), nullable=False),
        sa.Column("limiting_component_ids_json", sa.String(), nullable=False),
        sa.Column("data_provenance", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("timestamp_utc", "asset_id", name="uq_availability_snapshot_identity"),
    )
    op.create_index(
        "ix_availability_asset_time",
        "availability_snapshots",
        ["asset_id", "timestamp_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_availability_snapshots_asset_id"),
        "availability_snapshots",
        ["asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_availability_snapshots_timestamp_utc"),
        "availability_snapshots",
        ["timestamp_utc"],
        unique=False,
    )
    op.create_table(
        "battery_telemetry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("site_requested_power_mw", sa.Float(), nullable=False),
        sa.Column("site_actual_power_mw", sa.Float(), nullable=False),
        sa.Column("available_power_mw", sa.Float(), nullable=False),
        sa.Column("available_energy_mwh", sa.Float(), nullable=False),
        sa.Column("site_soc", sa.Float(), nullable=False),
        sa.Column("rte", sa.Float(), nullable=False),
        sa.Column("ambient_temperature_c", sa.Float(), nullable=False),
        sa.Column("available_racks", sa.Integer(), nullable=False),
        sa.Column("available_pcs", sa.Integer(), nullable=False),
        sa.Column("operating_mode", sa.String(length=32), nullable=False),
        sa.Column("alarm_count", sa.Integer(), nullable=False),
        sa.Column("data_provenance", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_battery_telemetry_asset_id"), "battery_telemetry", ["asset_id"], unique=False
    )
    op.create_index(
        "ix_battery_telemetry_asset_time",
        "battery_telemetry",
        ["asset_id", "timestamp_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_battery_telemetry_timestamp_utc"),
        "battery_telemetry",
        ["timestamp_utc"],
        unique=False,
    )
    op.create_table(
        "fault_ground_truth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fault_id", sa.String(length=64), nullable=False),
        sa.Column("fault_type", sa.String(length=64), nullable=False),
        sa.Column("component_id", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.Float(), nullable=False),
        sa.Column("ground_truth_label", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fault_ground_truth_component_id"),
        "fault_ground_truth",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fault_ground_truth_fault_id"), "fault_ground_truth", ["fault_id"], unique=False
    )
    op.create_index(
        op.f("ix_fault_ground_truth_timestamp_utc"),
        "fault_ground_truth",
        ["timestamp_utc"],
        unique=False,
    )
    op.create_table(
        "market_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("market_region", sa.String(length=32), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("series_type", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("data_provenance", sa.String(length=32), nullable=False),
        sa.Column("retrieved_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_content_hash", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=True),
        sa.Column("timeseries_mrid", sa.String(length=128), nullable=False),
        sa.Column("business_type", sa.String(length=32), nullable=True),
        sa.Column("process_type", sa.String(length=32), nullable=True),
        sa.Column("psr_type", sa.String(length=32), nullable=True),
        sa.Column("resolution", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "market_region",
            "metric",
            "timestamp_utc",
            "series_type",
            "timeseries_mrid",
            "raw_content_hash",
            name="uq_market_observation_source",
        ),
    )
    op.create_index(
        op.f("ix_market_data_market_region"), "market_data", ["market_region"], unique=False
    )
    op.create_index(op.f("ix_market_data_metric"), "market_data", ["metric"], unique=False)
    op.create_index(
        op.f("ix_market_data_raw_content_hash"), "market_data", ["raw_content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_market_data_timestamp_utc"), "market_data", ["timestamp_utc"], unique=False
    )
    op.create_index(
        "ix_market_region_metric_timestamp",
        "market_data",
        ["market_region", "metric", "timestamp_utc"],
        unique=False,
    )
    op.create_table(
        "model_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("prediction_name", sa.String(length=64), nullable=False),
        sa.Column("prediction_value", sa.Float(), nullable=False),
        sa.Column("actual_value", sa.Float(), nullable=True),
        sa.Column("residual_value", sa.Float(), nullable=True),
        sa.Column("prediction_horizon_hours", sa.Integer(), nullable=True),
        sa.Column("decision_threshold", sa.Float(), nullable=True),
        sa.Column("predicted_class", sa.Boolean(), nullable=True),
        sa.Column("prediction_provenance", sa.String(length=32), nullable=False),
        sa.Column("residual_provenance", sa.String(length=32), nullable=True),
        sa.Column("feature_set_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "timestamp_utc",
            "entity_id",
            "model_version",
            "prediction_name",
            name="uq_model_prediction_identity",
        ),
    )
    op.create_index(
        "ix_model_prediction_entity_time",
        "model_predictions",
        ["entity_id", "timestamp_utc"],
        unique=False,
    )
    op.create_index(
        "ix_model_prediction_name_time",
        "model_predictions",
        ["model_name", "timestamp_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_predictions_entity_id"), "model_predictions", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_predictions_model_version"),
        "model_predictions",
        ["model_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_predictions_timestamp_utc"),
        "model_predictions",
        ["timestamp_utc"],
        unique=False,
    )
    op.create_table(
        "monitoring_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observed_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric_scope", sa.String(length=32), nullable=False),
        sa.Column("subsystem", sa.String(length=64), nullable=False),
        sa.Column("metric_name", sa.String(length=96), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("asset_id", sa.String(length=64), nullable=True),
        sa.Column("reference_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reference_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column("data_provenance", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitoring_metrics_asset_id"), "monitoring_metrics", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_monitoring_metrics_metric_name"),
        "monitoring_metrics",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitoring_metrics_metric_scope"),
        "monitoring_metrics",
        ["metric_scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitoring_metrics_model_name"), "monitoring_metrics", ["model_name"], unique=False
    )
    op.create_index(
        op.f("ix_monitoring_metrics_observed_at_utc"),
        "monitoring_metrics",
        ["observed_at_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitoring_metrics_status"), "monitoring_metrics", ["status"], unique=False
    )
    op.create_index(
        "ix_monitoring_model_time",
        "monitoring_metrics",
        ["model_name", "observed_at_utc"],
        unique=False,
    )
    op.create_index(
        "ix_monitoring_scope_time",
        "monitoring_metrics",
        ["metric_scope", "observed_at_utc"],
        unique=False,
    )
    op.create_table(
        "pcs_telemetry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pcs_id", sa.String(length=64), nullable=False),
        sa.Column("requested_power_mw", sa.Float(), nullable=False),
        sa.Column("actual_power_mw", sa.Float(), nullable=False),
        sa.Column("efficiency", sa.Float(), nullable=False),
        sa.Column("temperature_c", sa.Float(), nullable=False),
        sa.Column("availability", sa.Boolean(), nullable=False),
        sa.Column("derating_factor", sa.Float(), nullable=False),
        sa.Column("alarm_state", sa.Boolean(), nullable=False),
        sa.Column("data_provenance", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pcs_telemetry_pcs_id"), "pcs_telemetry", ["pcs_id"], unique=False)
    op.create_index(
        "ix_pcs_telemetry_pcs_time", "pcs_telemetry", ["pcs_id", "timestamp_utc"], unique=False
    )
    op.create_index(
        op.f("ix_pcs_telemetry_timestamp_utc"), "pcs_telemetry", ["timestamp_utc"], unique=False
    )
    op.create_table(
        "price_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("forecast_origin_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("market_region", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("quantile", sa.Float(), nullable=False),
        sa.Column("predicted_price_eur_per_mwh", sa.Float(), nullable=False),
        sa.Column("horizon_minutes", sa.Integer(), nullable=False),
        sa.Column("feature_set_version", sa.String(length=32), nullable=False),
        sa.Column("data_provenance", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "forecast_origin_utc",
            "target_timestamp_utc",
            "market_region",
            "model_version",
            "quantile",
            name="uq_price_prediction_identity",
        ),
    )
    op.create_index(
        "ix_price_prediction_origin_target",
        "price_predictions",
        ["forecast_origin_utc", "target_timestamp_utc"],
        unique=False,
    )
    op.create_index(
        "ix_price_prediction_region_target",
        "price_predictions",
        ["market_region", "target_timestamp_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_predictions_forecast_origin_utc"),
        "price_predictions",
        ["forecast_origin_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_predictions_market_region"),
        "price_predictions",
        ["market_region"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_predictions_model_version"),
        "price_predictions",
        ["model_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_predictions_target_timestamp_utc"),
        "price_predictions",
        ["target_timestamp_utc"],
        unique=False,
    )
    op.create_table(
        "rack_telemetry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rack_id", sa.String(length=64), nullable=False),
        sa.Column("pcs_id", sa.String(length=64), nullable=False),
        sa.Column("soc", sa.Float(), nullable=False),
        sa.Column("soh_proxy", sa.Float(), nullable=False),
        sa.Column("voltage_v", sa.Float(), nullable=False),
        sa.Column("current_a", sa.Float(), nullable=False),
        sa.Column("temperature_mean_c", sa.Float(), nullable=False),
        sa.Column("temperature_min_c", sa.Float(), nullable=False),
        sa.Column("temperature_max_c", sa.Float(), nullable=False),
        sa.Column("temperature_spread_c", sa.Float(), nullable=False),
        sa.Column("voltage_spread_v", sa.Float(), nullable=False),
        sa.Column("requested_power_mw", sa.Float(), nullable=False),
        sa.Column("actual_power_mw", sa.Float(), nullable=False),
        sa.Column("charge_energy_mwh", sa.Float(), nullable=False),
        sa.Column("discharge_energy_mwh", sa.Float(), nullable=False),
        sa.Column("cumulative_throughput_mwh", sa.Float(), nullable=False),
        sa.Column("equivalent_full_cycles", sa.Float(), nullable=False),
        sa.Column("rte", sa.Float(), nullable=False),
        sa.Column("availability", sa.Boolean(), nullable=False),
        sa.Column("alarm_code", sa.String(length=64), nullable=True),
        sa.Column("operating_state", sa.String(length=32), nullable=False),
        sa.Column("data_provenance", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rack_telemetry_pcs_id"), "rack_telemetry", ["pcs_id"], unique=False)
    op.create_index(op.f("ix_rack_telemetry_rack_id"), "rack_telemetry", ["rack_id"], unique=False)
    op.create_index(
        "ix_rack_telemetry_rack_time", "rack_telemetry", ["rack_id", "timestamp_utc"], unique=False
    )
    op.create_index(
        op.f("ix_rack_telemetry_timestamp_utc"), "rack_telemetry", ["timestamp_utc"], unique=False
    )
    op.create_table(
        "revenue_at_risk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("start_timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("market_mode", sa.String(length=32), nullable=False),
        sa.Column("price_source", sa.String(length=64), nullable=False),
        sa.Column("healthy_gross_revenue_eur", sa.Float(), nullable=False),
        sa.Column("healthy_degradation_cost_eur", sa.Float(), nullable=False),
        sa.Column("healthy_net_revenue_eur", sa.Float(), nullable=False),
        sa.Column("current_gross_revenue_eur", sa.Float(), nullable=False),
        sa.Column("current_degradation_cost_eur", sa.Float(), nullable=False),
        sa.Column("current_net_revenue_eur", sa.Float(), nullable=False),
        sa.Column("revenue_at_risk_eur", sa.Float(), nullable=False),
        sa.Column("revenue_at_risk_fraction", sa.Float(), nullable=True),
        sa.Column("power_derating_impact_eur", sa.Float(), nullable=False),
        sa.Column("energy_capacity_impact_eur", sa.Float(), nullable=False),
        sa.Column("efficiency_impact_eur", sa.Float(), nullable=False),
        sa.Column("availability_impact_eur", sa.Float(), nullable=False),
        sa.Column("interaction_unattributed_eur", sa.Float(), nullable=False),
        sa.Column("model_or_price_version", sa.String(length=128), nullable=False),
        sa.Column("capability_version", sa.String(length=64), nullable=False),
        sa.Column("price_dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("capability_dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("optimization_config_hash", sa.String(length=64), nullable=False),
        sa.Column("calculation_hash", sa.String(length=64), nullable=False),
        sa.Column("attribution_json", sa.String(), nullable=False),
        sa.Column("data_provenance", sa.String(length=64), nullable=False),
        sa.Column("disclaimer", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calculation_hash", name="uq_revenue_at_risk_calculation"),
    )
    op.create_index(
        op.f("ix_revenue_at_risk_asset_id"), "revenue_at_risk", ["asset_id"], unique=False
    )
    op.create_index(
        "ix_revenue_at_risk_asset_interval",
        "revenue_at_risk",
        ["asset_id", "start_timestamp_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_revenue_at_risk_calculation_hash"),
        "revenue_at_risk",
        ["calculation_hash"],
        unique=True,
    )
    op.create_table(
        "pcs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pcs_id", sa.String(length=64), nullable=False),
        sa.Column("asset_pk", sa.Integer(), nullable=False),
        sa.Column("rated_power_mw", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_pk"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pcs_pcs_id"), "pcs", ["pcs_id"], unique=True)
    op.create_table(
        "racks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rack_id", sa.String(length=64), nullable=False),
        sa.Column("pcs_pk", sa.Integer(), nullable=False),
        sa.Column("rated_power_mw", sa.Float(), nullable=False),
        sa.Column("rated_energy_mwh", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pcs_pk"],
            ["pcs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_racks_rack_id"), "racks", ["rack_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_racks_rack_id"), table_name="racks")
    op.drop_table("racks")
    op.drop_index(op.f("ix_pcs_pcs_id"), table_name="pcs")
    op.drop_table("pcs")
    op.drop_index(op.f("ix_revenue_at_risk_calculation_hash"), table_name="revenue_at_risk")
    op.drop_index("ix_revenue_at_risk_asset_interval", table_name="revenue_at_risk")
    op.drop_index(op.f("ix_revenue_at_risk_asset_id"), table_name="revenue_at_risk")
    op.drop_table("revenue_at_risk")
    op.drop_index(op.f("ix_rack_telemetry_timestamp_utc"), table_name="rack_telemetry")
    op.drop_index("ix_rack_telemetry_rack_time", table_name="rack_telemetry")
    op.drop_index(op.f("ix_rack_telemetry_rack_id"), table_name="rack_telemetry")
    op.drop_index(op.f("ix_rack_telemetry_pcs_id"), table_name="rack_telemetry")
    op.drop_table("rack_telemetry")
    op.drop_index(op.f("ix_price_predictions_target_timestamp_utc"), table_name="price_predictions")
    op.drop_index(op.f("ix_price_predictions_model_version"), table_name="price_predictions")
    op.drop_index(op.f("ix_price_predictions_market_region"), table_name="price_predictions")
    op.drop_index(op.f("ix_price_predictions_forecast_origin_utc"), table_name="price_predictions")
    op.drop_index("ix_price_prediction_region_target", table_name="price_predictions")
    op.drop_index("ix_price_prediction_origin_target", table_name="price_predictions")
    op.drop_table("price_predictions")
    op.drop_index(op.f("ix_pcs_telemetry_timestamp_utc"), table_name="pcs_telemetry")
    op.drop_index("ix_pcs_telemetry_pcs_time", table_name="pcs_telemetry")
    op.drop_index(op.f("ix_pcs_telemetry_pcs_id"), table_name="pcs_telemetry")
    op.drop_table("pcs_telemetry")
    op.drop_index("ix_monitoring_scope_time", table_name="monitoring_metrics")
    op.drop_index("ix_monitoring_model_time", table_name="monitoring_metrics")
    op.drop_index(op.f("ix_monitoring_metrics_status"), table_name="monitoring_metrics")
    op.drop_index(op.f("ix_monitoring_metrics_observed_at_utc"), table_name="monitoring_metrics")
    op.drop_index(op.f("ix_monitoring_metrics_model_name"), table_name="monitoring_metrics")
    op.drop_index(op.f("ix_monitoring_metrics_metric_scope"), table_name="monitoring_metrics")
    op.drop_index(op.f("ix_monitoring_metrics_metric_name"), table_name="monitoring_metrics")
    op.drop_index(op.f("ix_monitoring_metrics_asset_id"), table_name="monitoring_metrics")
    op.drop_table("monitoring_metrics")
    op.drop_index(op.f("ix_model_predictions_timestamp_utc"), table_name="model_predictions")
    op.drop_index(op.f("ix_model_predictions_model_version"), table_name="model_predictions")
    op.drop_index(op.f("ix_model_predictions_entity_id"), table_name="model_predictions")
    op.drop_index("ix_model_prediction_name_time", table_name="model_predictions")
    op.drop_index("ix_model_prediction_entity_time", table_name="model_predictions")
    op.drop_table("model_predictions")
    op.drop_index("ix_market_region_metric_timestamp", table_name="market_data")
    op.drop_index(op.f("ix_market_data_timestamp_utc"), table_name="market_data")
    op.drop_index(op.f("ix_market_data_raw_content_hash"), table_name="market_data")
    op.drop_index(op.f("ix_market_data_metric"), table_name="market_data")
    op.drop_index(op.f("ix_market_data_market_region"), table_name="market_data")
    op.drop_table("market_data")
    op.drop_index(op.f("ix_fault_ground_truth_timestamp_utc"), table_name="fault_ground_truth")
    op.drop_index(op.f("ix_fault_ground_truth_fault_id"), table_name="fault_ground_truth")
    op.drop_index(op.f("ix_fault_ground_truth_component_id"), table_name="fault_ground_truth")
    op.drop_table("fault_ground_truth")
    op.drop_index(op.f("ix_battery_telemetry_timestamp_utc"), table_name="battery_telemetry")
    op.drop_index("ix_battery_telemetry_asset_time", table_name="battery_telemetry")
    op.drop_index(op.f("ix_battery_telemetry_asset_id"), table_name="battery_telemetry")
    op.drop_table("battery_telemetry")
    op.drop_index(
        op.f("ix_availability_snapshots_timestamp_utc"), table_name="availability_snapshots"
    )
    op.drop_index(op.f("ix_availability_snapshots_asset_id"), table_name="availability_snapshots")
    op.drop_index("ix_availability_asset_time", table_name="availability_snapshots")
    op.drop_table("availability_snapshots")
    op.drop_index(op.f("ix_assets_asset_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_anomaly_events_start_timestamp"), table_name="anomaly_events")
    op.drop_index(op.f("ix_anomaly_events_component_id"), table_name="anomaly_events")
    op.drop_index(op.f("ix_anomaly_events_anomaly_event_id"), table_name="anomaly_events")
    op.drop_index("ix_anomaly_component_start", table_name="anomaly_events")
    op.drop_table("anomaly_events")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_component_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_asset_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_key"), table_name="alerts")
    op.drop_index("ix_alert_status_priority", table_name="alerts")
    op.drop_index("ix_alert_asset_status", table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
