[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[server]
headless = true

[theme]
base = "dark"
primaryColor = "#51D88A"
backgroundColor = "#081118"
secondaryBackgroundColor = "#101B26"
textColor = "#F2F7FB"
